name: Build linux release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      # install libxcb-xinerama0 to fix "Could not load the Qt platform plugin 'xcb'"
      # https://forum.qt.io/post/610967
      run: |
        sudo apt-get install libxcb-xinerama0
        python -m pip install --upgrade pip
        pip install -r requirements_build.txt

    - name: Build package
      run: pyinstaller -F run_gui.py -i "pdf.ico" --distpath . -n "pdfdir"  --noconsole

    - name: Build debug package
      run: pyinstaller -F run_gui.py -i "pdf.ico" --distpath . -n "pdfdir_debug"

    - name: Prepare file
      run: |
        chmod +x pdfdir
        zip -r pdfdir_ubuntu.zip pdfdir

    - name: Prepare debug file
      run: |
        chmod +x pdfdir_debug
        zip -r pdfdir_debug_ubuntu.zip pdfdir_debug

    - name: Upload package
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          pdfdir_ubuntu.zip
          pdfdir_debug_ubuntu.zip
