name: Build macos-14 release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_build_addon.txt
        pip install Pillow
    
    - name: Build package
      run: pyinstaller -D run_gui.py -i "pdf.ico" --distpath . -n "pdfdir"  --noconsole

    - name: Prepare file
      run: |
        chmod +x pdfdir.app
        zip -r pdfdir_mac_silicon.zip pdfdir.app
    

    - name: Upload package
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          pdfdir_mac_silicon.zip